# # 1️⃣ Use official Node image
# FROM node:20.20.0-alpine3.23

# # 2️⃣ Create app directory inside container
# WORKDIR /app

# # 3️⃣ Copy package files
# COPY package*.json ./

# # 4️⃣ Install dependencies
# RUN npm install

# # 5️⃣ Copy rest of application code
# COPY . .

# RUN npm run build

# # 6️⃣ Expose the port your app runs on
# EXPOSE 5000


# # # 7️⃣ Start the application
# CMD ["node", "dist/server.js"]


FROM node:20.20.0-alpine3.23

WORKDIR /app

COPY package*.json .
COPY tsconfig.json .

RUN npm install 

COPY dist/ dist/
COPY src/ src/
COPY .env .
COPY .env.dev .

RUN npm run build

EXPOSE 5000

CMD ["node","dist/server.js"]
